engines:
  phpmd:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
      - BUG
  duplication:
    enabled: true
    config:
      languages:
      - php
exclude_paths:
- ".codeclimate.yml"
- "**/vendor/**/*"
